version: '3'

services:
  app-dev:
    image: forms-dev
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next