name: Database Backup

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Postgres Dump Backup
        uses: tj-actions/pg-dump@v3
        with:
          database_url: ${{ secrets.DATABASE_URL }}
          postgresql_version: "15"
          path: 'backups/backup.sql'
          options: '-O'
          
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
        
      - name: Rename backup
        run: mv backups/backup.sql backups/backup_${{ steps.date.outputs.date }}.sql
        
      - name: Upload backup
        uses: actions/upload-artifact@v4
        with:
          name: Database backup
          path: backups/*.sql
