name: E2E tests

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 21
      CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run Cypress tests
        run: npx cypress run
